# Regenerates assets\js\pages-manifest.js from the .html files inside the tools\ folder.
# Usage:  scan-pages.ps1          -> run once
#         scan-pages.ps1 -Watch   -> keep running, auto-update when files are added/removed
param([switch]$Watch)
$root  = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$tools = Join-Path $root 'tools'
$out   = Join-Path $root 'assets\js\pages-manifest.js'

function Get-Pages {
    Get-ChildItem -LiteralPath $tools -File |
        Where-Object { $_.Extension -match '^\.html?$' } |
        Sort-Object Name | ForEach-Object { $_.Name }
}
function Write-Manifest($names) {
    $items = ($names | ForEach-Object { '  "' + ($_ -replace '\\','\\\\' -replace '"','\"') + '"' }) -join ",`n"
    $js = @"
/**
 * Auto-generated by scripts/scan-pages.ps1 - do not edit by hand.
 * Generated at: $((Get-Date).ToString('s'))
 */
(function (root) {
  var pages = [
$items
];
  root.__DYNAMIC_PAGES__ = pages;
})(window);
"@
    [System.IO.File]::WriteAllText($out, $js, (New-Object System.Text.UTF8Encoding($false)))
}

$last = @(Get-Pages)
Write-Manifest $last
Write-Host "Manifest updated: $($last.Count) pages"
if ($Watch) {
    Write-Host "Watching tools folder... (Ctrl+C to stop)"
    while ($true) {
        Start-Sleep -Seconds 2
        $now = @(Get-Pages)
        if (($now -join '|') -ne ($last -join '|')) {
            $last = $now
            Write-Manifest $last
            Write-Host "$(Get-Date -Format T)  Manifest updated: $($last.Count) pages"
        }
    }
}
